name: build-client

on:
  [push, pull_request]

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code from repo
      uses: actions/checkout@v2

    - name: Run linter
      run: |
        npm i -g yarn
        yarn
        yarn lint

  tests-job:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code from repo
      uses: actions/checkout@v2

    - name: Run tests on code
      run: yarn && yarn test
