name: build-client

on:
    pull_request:
        branches:
            - dev

jobs:
    lint-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code from repo
              uses: actions/checkout@v2

            - name: Run linter
              run: |
                  npm i -g yarn
                  yarn
                  yarn lint

    tests-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code from repo
              uses: actions/checkout@v2

            - name: Run tests on code
              run: yarn && yarn test

            - name: Discord notification build failure
              if: ${{ failure() }}
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
                  DISCORD_USERNAME: Failure
              uses: Ilshidur/action-discord@master
              with:
                  args: 'Tests on PR https://github.com/WildCodeSchool/2109-wns-remote3-jahbaf-client/pull/{{ EVENT_PAYLOAD.pull_request.id }} failed'

            - name: Discord notification success
              if: ${{ success() }}
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
                  DISCORD_USERNAME: Success
              uses: Ilshidur/action-discord@master
              with:
                  args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
